# Generated by Django 4.1.7 on 2023-03-08 17:38

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoria', max_length=50)),
                ('descripcion_corta', models.TextField(blank=True, help_text='Descripcion corta (max 200 caracteres)', max_length=200)),
                ('descripcion_larga', models.TextField(blank=True, help_text='Descripcion larga', max_length=1000)),
                ('meta_titulo', models.SlugField(unique=True)),
                ('destacado', models.BooleanField(help_text='Destacado, aparece en la pagina principal')),
                ('imagen1', models.ImageField(blank=True, upload_to='uploads/')),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha de creación del producto')),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='catalogo.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=50)),
                ('precio', models.FloatField(help_text='Precio del producto')),
                ('activo', models.BooleanField(help_text='Activo, aparece en catalogo')),
                ('destacado', models.BooleanField(help_text='Destacado, aparece en la pagina principal')),
                ('stock', models.IntegerField(help_text='Unidades en stock')),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha de creación del producto')),
                ('imagen1', models.ImageField(upload_to='uploads/')),
                ('imagen2', models.ImageField(blank=True, upload_to='uploads/')),
                ('imagen3', models.ImageField(blank=True, upload_to='uploads/')),
                ('meta_titulo', models.SlugField(unique=True)),
                ('categoria', models.ManyToManyField(related_name='cat', to='catalogo.categoria')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
