# Generated by Django 4.1.7 on 2023-03-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_options_producto_imagen2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoria', max_length=50)),
                ('descripcion_corta', models.TextField(help_text='Descripcion corta (max 200 caracteres)', max_length=200)),
                ('descripcion_larga', models.TextField(help_text='Descripcion larga', max_length=1000)),
                ('meta_titulo', models.SlugField(unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, help_text='Fecha de creación del producto')),
                ('categoria_padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='catalogo.categoria')),
            ],
        ),
    ]
