# Generated by Django 4.1.7 on 2023-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(to='catalogo.categoria'),
        ),
    ]
