# Generated by Django 4.2.1 on 2023-05-07 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0003_producto_porcentajedescuento"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="fecha_modificacion",
            field=models.DateField(
                auto_now=True, help_text="Fecha de modificación de la categoria"
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="fecha_modificacion",
            field=models.DateField(auto_now=True, help_text="Fecha de modificación"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="fecha_creacion",
            field=models.DateField(
                auto_now_add=True, help_text="Fecha de creación de la categoria"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ManyToManyField(to="catalogo.categoria"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateField(auto_now_add=True, help_text="Fecha de creación"),
        ),
        migrations.CreateModel(
            name="ImagenProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, help_text="Fecha de creación de la categoria"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, help_text="Fecha de modificación de la categoria"
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogo.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, help_text="Fecha de creación de la categoria"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, help_text="Fecha de modificación de la categoria"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito",
                "verbose_name_plural": "s",
            },
        ),
    ]
