# Generated by Django 4.1.7 on 2023-03-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_corta',
            field=models.TextField(blank=True, help_text='Descripcion corta (max 200 caracteres)', max_length=200),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_larga',
            field=models.TextField(blank=True, help_text='Descripcion larga', max_length=1000),
        ),
    ]
