# Generated by Django 4.1.7 on 2023-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_categoria_categoria_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='meta_titulo',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
