# Generated by Django 4.2.1 on 2023-05-07 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0005_remove_producto_imagen1_remove_producto_imagen2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categoria",
            old_name="imagen1",
            new_name="imagen",
        ),
    ]
