# Generated by Django 4.1.7 on 2023-03-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_meta_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='destacado',
            field=models.BooleanField(default=True, help_text='Destacado, aparece en la pagina principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=True, help_text='Destacado, aparece en la pagina principal'),
            preserve_default=False,
        ),
    ]
