# Generated by Django 4.2.1 on 2023-05-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0006_rename_imagen1_categoria_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="categoria",
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogo.categoria",
            ),
        ),
    ]
