# Generated by Django 4.2.1 on 2023-05-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0007_remove_producto_categoria_producto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="referencia",
            field=models.CharField(
                default="1231A4664QQG",
                help_text="Referencia del producto",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
