# Generated by Django 4.1.7 on 2023-03-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_categoria_destacado_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen1',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(related_name='cat', to='catalogo.categoria'),
        ),
    ]
