# Generated by Django 4.2.1 on 2023-05-07 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogo", "0008_producto_referencia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Carrito",
        ),
    ]
